### ISSUE TITLE
Multiprocessing support

### ISSUE THREAD

**Issue by ghost** [danilobellini/fractals#1]
Hello,

Phenomenal work with the fractal package!
Any plans for multiprocessing implementation?

Thanks,
coast

**Comment by danilobellini** [comment]
Thank you! =)

I never thought about parallelizing this project, but it would clearly benefit from optimizations. As each pixel is independent in the `generate_fractal` function, a parallel "map" that builds the fractal image would be a straightforward approach for optimization. It would be great an extra parameter to control the parallelism but starting with `multiprocessing.cpu_count()` sounds fair. This probably isn't the best optimization approach (as, e.g., symmetries and some sort of same-valued grouping could be explored; perhaps it's possible to use specific technologies/architectures like CUDA), but it would help and doesn't seem like a toil.

I'll be waiting for a pull request.
